### ISSUE TITLE
Bot crashing

### ISSUE THREAD

**Issue by Aviortheking** [tcgdex/bot#61]
```
2022-09-26T20:09:22.637998494Z                                         ^
2022-09-26T20:09:22.637976934Z       const existing = channel.messages.cache.get(data.id);
2022-09-26T20:09:22.637864424Z /app/node_modules/discord.js/src/client/actions/MessageCreate.js:13
2022-09-26T20:09:22.638219457Z Node.js v18.9.0
2022-09-26T20:09:22.638212314Z 
2022-09-26T20:09:22.638204607Z     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:517:14)
2022-09-26T20:09:22.638196840Z     at Receiver.emit (node:events:513:28)
2022-09-26T20:09:22.638189197Z     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:983:20)
2022-09-26T20:09:22.638181690Z     at WebSocket.emit (node:events:513:28)
2022-09-26T20:09:22.638174004Z     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
2022-09-26T20:09:22.638165893Z     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
2022-09-26T20:09:22.638129820Z     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
2022-09-26T20:09:22.638122047Z     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
2022-09-26T20:09:22.638114057Z     at module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2022-09-26T20:09:22.638102713Z     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:13:41)
2022-09-26T20:09:22.638094793Z TypeError: Cannot read properties of undefined (reading 'cache')
```

**Comment by Aviortheking** [comment]
fixed with new bot architecture
